pull_request_rules:
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
  - name: automatic merge for scala-steward pull requests affecting build.sbt
    conditions:
      - author=rodobarcaaa
      - check-success=build (ubuntu-latest, 8)
      - check-success=build (ubuntu-latest, 11)
      - check-success=build (ubuntu-latest, 17)      
      - check-success=sonar
      - "#files=1"
      - files=build.sbt
    actions:
      merge:
        method: rebase
  - name: automatic merge for scala-steward pull requests affecting project plugins.sbt
    conditions:
      - author=rodobarcaaa
      - check-success=build (ubuntu-latest, 8)
      - check-success=build (ubuntu-latest, 11)
      - check-success=build (ubuntu-latest, 17)      
      - check-success=sonar
      - "#files=1"
      - files=project/plugins.sbt
    actions:
      merge:
        method: rebase
  - name: semi-automatic merge for scala-steward pull requests
    conditions:
      - author=rodobarcaaa
      - check-success=build (ubuntu-latest, 8)
      - check-success=build (ubuntu-latest, 11)
      - check-success=build (ubuntu-latest, 17)      
      - check-success=sonar
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: rebase
  - name: automatic merge for scala-steward pull requests affecting project build.properties
    conditions:
      - author=rodobarcaaa
      - check-success=build (ubuntu-latest, 8)
      - check-success=build (ubuntu-latest, 11)
      - check-success=build (ubuntu-latest, 17)      
      - check-success=sonar
      - "#files=1"
      - files=project/build.properties
    actions:
      merge:
        method: rebase
  - name: automatic merge for scala-steward pull requests affecting .scalafmt.conf
    conditions:
      - author=rodobarcaaa
      - check-success=build (ubuntu-latest, 8)
      - check-success=build (ubuntu-latest, 11)
      - check-success=build (ubuntu-latest, 17)      
      - check-success=sonar
      - "#files=1"
      - files=.scalafmt.conf
    actions:
      merge:
        method: rebase
