addSbtPlugin("org.scalameta"          % "sbt-scalafmt"  % "2.4.2")
addSbtPlugin("com.github.sbt"         % "sbt-release"   % "1.1.0")
addSbtPlugin("org.scoverage"          % "sbt-scoverage" % "1.6.1")
addSbtPlugin("com.sonar-scala"        % "sbt-sonar"     % "2.3.0")
addSbtPlugin("com.sksamuel.scapegoat" % "sbt-scapegoat" % "1.1.1")
