addSbtPlugin("org.scalameta"   % "sbt-scalafmt"        % "2.5.6")
addSbtPlugin("ch.epfl.scala"   % "sbt-scalafix"        % "0.13.0")
addSbtPlugin("org.scoverage"   % "sbt-scoverage"       % "2.4.4")
addSbtPlugin("com.sonar-scala" % "sbt-sonar"           % "2.3.0")
addSbtPlugin("com.github.sbt"  % "sbt-release"         % "1.1.0")
addSbtPlugin("com.github.sbt"  % "sbt-native-packager" % "1.10.0")
