name: staging

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  staging:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Dispatch Auto Deploy
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.USER_GITHUB_TOKEN }}
          repository: rodobarcaaa/tapir-http4s-seed
          event-type: deploy
          client-payload: '{"tag": "main", "environment": "staging"}'
